version: '3'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=foods
    volumes:
      - "./foods_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  web:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      command: python manage.py runserver 0.0.0.0:8000
      container_name: django_web
      environment:
      - DATABASE_URL="postgres://root:root@pgdatabase:5432/foods"
      volumes:
      - .:/code
      ports:
      - "8000:8000"
      depends_on:
      - pgdatabase      
      